apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-frasaja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-frasaja
  template:
    metadata:
      labels:
        app: kubernetes-frasaja
    spec:
      containers:
      - name: kubernetes-frasaja
        image: kubernetes-frasaja:v1
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /test
          name: host-mount
      volumes:
      - name: docker-sock-volume
        hostPath:
          # location on host
          path: /var/run/docker.sock
          # this field is optional
          type: Socket
      - name: host-mount
        hostPath:
          path: /mount-9p
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: kubernetes-frasaja
spec:
  type: NodePort
  selector:
    app: kubernetes-frasaja
  ports:
  - name: kubernetes-frasaja
    port: 8080
    targetPort: 8080
